#optional

name: CI/CD for dev branch

#trigger 
on:

  push:
    branches: [dev]


#jobs 
jobs:
  demo-test:
    runs-on: [ostad-tag]
    steps:
    #transer code ..must
    - name: Checkout Code
      uses: actions/checkout@v3
    # optional based on Project [install node with 16 version]
    - name: Setup enviroment
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    #
    - name: install dependency 
      run: | 
        npm install
        
    
    - name: Run test 
      run: |
        echo "Running Test . . . . "
        npm test >test-result.txt || true 

    - name: Upload the test-result
      uses: actions/upload-artifact@v4
      with:
        name: test-result
        path: test-result.txt
      
  deploy:
    needs: demo-test
    runs-on: [ostad-tag]

    steps:
    #transer code ..must
    - name: Checkout Code
      uses: actions/checkout@v3
    

    - name: Download the test-result
      uses: actions/download-artifact@v4
      with:
        name: test-result

    - name: Show the test result
      run: cat test-result.txt
    

     # optional based on Project [install node with 16 version]
    - name: Setup enviroment
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: install dependency 
      run: | 
        npm install

    
    - name: Live Application
      run: |
        npm install -g pm2
        pm2 delete all || true
        pm2 start index.js --name ostad-app


